module Orthoses
  VERSION: String

  class ConstLoadError < StandardError
    attr_reader root: Module
    attr_reader const: Symbol
    attr_reader error: untyped
    def initialize: (root: Module, const: Symbol, error: untyped) -> void
  end

  class NameSpaceError < StandardError
  end

  attr_accessor self.logger: ::Logger

  type store = Hash[String, Orthoses::Content]

  interface _Call
    def call: () -> Orthoses::store
  end
  interface _MiddleWare
    include Orthoses::_Call
  end
end
