# THIS IS GENERATED CODE from `$ rake sig`

# CallTracer::Lazy is possible to perform a trace
# equivalent to CallTracer before method is defined.
#     scope = CallTracerLazy.new
#     scope.trace("ActiveRecord::Base#scope") do
#       require 'active_record/all'
#       @loader.call
#     end
#     scope.captures.each do |capture|
#       capture.argument[:name]
#       capture.argument[:body]
#       capture.argument[:block]
#     end
class Orthoses::CallTracer::Lazy
  def initialize: () -> void
  def trace: (String name) ?{ () -> untyped } -> untyped
  attr_reader captures: Array[untyped]
end
