# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::CallTracer::Lazy
  def initialize: () -> void
  def trace: (String name) ?{ () -> untyped } -> untyped
  attr_reader captures: Array[untyped]
end
