module Orthoses
  module Outputable
    class AvoidRecursiveAncestorError
      @loader: Orthoses::_Call
      def initialize: (Orthoses::_Call loader) -> void
      def call: () -> Orthoses::store
    end
  end
end
