module Orthoses
  class Trace
    class Attribute
      include Orthoses::Trace::Targetable

      def initialize: (Orthoses::_Call loader, patterns: Array[String] | Orthoses::Trace::_CallablePatterns, ?sort_union_types: bool?) -> void
      def call: () -> Orthoses::store
    end
  end
end
