module Orthoses
  class Trace
    class Method
      include Orthoses::Trace::Targetable

      def initialize: (Orthoses::_Call loader, patterns: Array[String], ?sort_union_types: bool?) -> void
      def call: () -> Orthoses::store
    end
  end
end
