module Orthoses
  class Trace
    class Method
      include Orthoses::Trace::Targetable

      def initialize: (Orthoses::_Call loader, patterns: Array[String], trace_point_filter: Orthoses::Trace::_CallableFilter?, ?sort_union_types: bool?) -> void
      def call: () -> Orthoses::store
    end
  end
end
