# THIS IS GENERATED CODE from `$ rake sig`

# AvoidRecursiveAncestorError is an internal middleware
# It's using on orthoses/outputable.rb
class Orthoses::Outputable::AvoidRecursiveAncestorError
  def initialize: (Orthoses::_Call loader) -> void
  def call: () -> Orthoses::store
  private def collect_mixin_recursive: (untyped store, untyped name, untyped mixins) -> untyped
  @loader: Orthoses::_Call
end
