# THIS IS GENERATED CODE from `$ rake sig`

# Constantizable is an internal middleware
# It's using on orthoses/outputable.rb
class Orthoses::Outputable::ConstantizableFilter
  def initialize: (untyped loader) -> void
  def call: () -> untyped
end
