# THIS IS GENERATED CODE from `$ rake sig`

# internal
class Orthoses::Utils::TypeList
  @types: untyped
  def initialize: (untyped types) -> void
  def inject: () -> untyped
  private def normalize: () -> self
  BOOL_TYPE: RBS::Types::Bases::Bool
  FALSE_TYPE: RBS::Types::Literal
  NIL_TYPE: RBS::Types::Bases::Nil
  TRUE_TYPE: RBS::Types::Literal
  UNTYPED: RBS::Types::Bases::Any
end
