# THIS IS GENERATED CODE from `$ rake generate_self_sig`

# internal
class Orthoses::Utils::TypeList
  def initialize: (untyped types) -> void
  def inject: () -> untyped
  FALSE_TYPE: RBS::Types::Literal
  NIL_TYPE: RBS::Types::Bases::Nil
  TRUE_TYPE: RBS::Types::Literal
  UNTYPED: RBS::Types::Bases::Any
end
