module Minitest::Test::LifecycleHooks
  def before_setup: () -> void
  def setup: () -> void
  def after_setup: () -> void
  def before_teardown: () -> void
  def teardown: () -> void
  def after_teardown: () -> void
end
