# THIS IS GENERATED CODE from `$ rake sig`

module Orthoses
  VERSION: "1.7.0"

  attr_accessor self.logger: ::Logger

  type store = Hash[String, Orthoses::Content]

  INSTANCE_METHOD_METHOD: UnboundMethod

  METHOD_METHOD: UnboundMethod
end
