# THIS IS GENERATED CODE from `$ rake generate_self_sig`

module Orthoses
  VERSION: "0.10.0"
  attr_accessor self.logger: ::Logger
  type store = Hash[String, Orthoses::Content]
  INSTANCE_METHOD_METHOD: UnboundMethod
  METHOD_METHOD: UnboundMethod
end
