# THIS IS GENERATED CODE from `$ rake generate_self_sig`

module Orthoses::Attribute::Hook : Module
  def attr: (*untyped names) -> untyped

  def attr_accessor: (*untyped names) -> untyped

  def attr_reader: (*untyped names) -> untyped

  def attr_writer: (*untyped names) -> untyped
end
