# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Content::DuplicationChecker
  def initialize: (untyped decl) -> void
  def update_decl: () -> untyped
  private
  def drop_known_method_definition: (untyped uniq_map) -> untyped
  def member_to_s: (untyped member) -> untyped
  def member_key: (untyped member) -> untyped
end
