# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Content::Environment
  @load_env: RBS::Environment
  @known_env: RBS::Environment
  @method_definition_filter: method_definition_filter?
  @alias_filter: alias_filter?
  @constant_filter: constant_filter?
  @mixin_filter: mixin_filter?
  @attribute_filter: attribute_filter?
  def self.load_from_paths: (untyped paths) -> untyped
  def initialize: (?method_definition_filter: method_definition_filter?, ?alias_filter: alias_filter?, ?constant_filter: constant_filter?, ?mixin_filter: mixin_filter?, ?attribute_filter: attribute_filter?) -> void
  def <<: (RBS::AST::Declarations::t decl) -> RBS::Environment
  def write_to: (store: Orthoses::store) -> void
  def each: () { (Orthoses::Content) -> void } -> void
  # Avoid `RBS::GenericParameterMismatchError` from like rbs_prototype_rb
  #     class Array # <= RBS::GenericParameterMismatchError
  #     end
  private def avoid_generic_parameter_mismatch_error: () -> untyped
  private def decls_to_lines: (untyped decls) -> untyped
  type method_definition_filter = ^(RBS::AST::Members::MethodDefinition) -> boolish
  type alias_filter = ^(RBS::AST::Members::Alias) -> boolish
  type constant_filter = ^(RBS::AST::Declarations::Constant) -> boolish
  type mixin_filter = ^(RBS::AST::Members::Mixin) -> boolish
  type attribute_filter = ^(RBS::AST::Members::Attribute) -> boolish
end
