# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Content::HeaderBuilder
  @env: untyped
  @resolver: untyped
  def initialize: (env: untyped) -> void
  def build: (entry: untyped, ?name_hint: untyped?) -> untyped
  private def build_module: (entry: untyped, ?name_hint: untyped?) -> ::String
  private def build_class: (entry: untyped, ?name_hint: untyped?) -> ::String
  private def build_super_class: (untyped primary) -> (nil | untyped)
  private def build_interface: (entry: untyped, ?name_hint: untyped?) -> ::String
  private def build_context: (entry: untyped) -> untyped
  private def name_and_params: (untyped name, untyped params) -> ::String
  private def name_and_args: (untyped name, untyped args) -> (::String | nil)
  include RBS::Environment::ContextUtil
end
