# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Attribute
  @loader: Orthoses::_Call
  def initialize: (Orthoses::_Call loader) -> void
  def call: () -> Orthoses::store
  CALL_GRAPH: Hash[untyped, untyped]
end
