# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Autoload
  @loader: untyped
  def initialize: (untyped loader) -> void
  def call: () -> untyped
end

module Orthoses::Autoload::Hook
  def autoload: (untyped name, untyped path) -> untyped
end
