# THIS IS GENERATED CODE from `$ rake sig`

# Middleware builder like the Rack
#   Builder.new do
#     use Orthoses::CreateFileByName
#     use Orthoses::Constant
#     use Orthoses::Mixin
#     use Orthoses::Walk,
#       root: "Foo"
#     run ->() { require 'foo' }
#   end
class Orthoses::Builder
  def initialize: () ?{ () [self: Orthoses::Builder] -> untyped } -> void
  def use: (untyped middleware, *untyped args, **untyped key) ?{ (*untyped, **untyped) -> untyped } -> untyped
  def run: (untyped loader) -> untyped
  def reset_runner: (untyped loader) -> untyped
  def to_loader: () -> untyped
  def call: () -> Orthoses::store
end
