# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::CallTracer
  @captures: untyped
  @target_tp: untyped
  def initialize: () -> void
  def trace: (Method | UnboundMethod) ?{ () -> untyped } -> untyped
  attr_accessor captures: Array[Capture]
end
