# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::CallTracer
  def initialize: () -> void
  def trace: (Method | UnboundMethod) ?{ () -> untyped } -> untyped
  attr_accessor captures: Array[Capture]
end
