# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class ::Orthoses::Constant
  @loader: ::Orthoses::_Call
  include ::Orthoses::_MiddleWare
  def initialize: (::Orthoses::_Call loader, ?if: ^(Module, Symbol, untyped) -> boolish, ?on_error: ^(::Orthoses::ConstLoadError) -> void) -> void
end
