# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::ConstLoadError < ::StandardError
  @root: untyped
  @const: untyped
  @error: untyped
  def initialize: (root: Module, const: Symbol, error: untyped) -> void
  def message: () -> ::String
  attr_reader root: Module
  attr_reader const: Symbol
  attr_reader error: untyped
end
