# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::ConstLoadError < ::StandardError
  def initialize: (root: Module, const: Symbol, error: untyped) -> void
  def message: () -> ::String
  attr_reader root: Module
  attr_reader const: Symbol
  attr_reader error: untyped
end
