# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Constant
  def initialize: (Orthoses::_Call loader, strict: bool, ?if: ^(Module, Symbol, untyped) -> boolish, ?on_error: ^(Orthoses::ConstLoadError) -> void) -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
  @strict: bool
  @if: ^(Module mod, Symbol const, untyped val, String rbs) -> boolish?
  @on_error: ^(Orthoses::ConstLoadError) -> void | nil
end
