# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Content
  attr_reader name: String
  attr_reader body: Array[String]
  attr_accessor header: String?
  def initialize: (name: String) -> void
  def <<: (String) -> void
  def concat: (Array[String]) -> void
  def to_rbs: () -> String
  def to_decl: () -> untyped

  private
  def original_rbs: () -> ::String

  def uniqed_body_string: () -> String
  def uniqed_body_decl: () -> RBS::AST::Declarations::t
  def auto_header: () -> (nil | untyped)
  def temporary_type_params: (untyped name) -> untyped
  def type_params: (untyped name) -> untyped
end
