# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Content
  def initialize: (name: String) -> void
  def <<: (String) -> void
  def concat: (Array[String]) -> void
  def empty?: () -> untyped
  def interface?: () -> untyped
  def delete: (untyped val) -> untyped
  def to_rbs: () -> String
  def to_decl: () -> untyped
  def uniq!: () -> untyped
  def sort!: () -> untyped
  def original_rbs: () -> untyped
  def auto_header: () -> (nil | untyped)
  private def build_super_class: (untyped val) -> (nil | ::String)
  private def decl_to_lines: (untyped decl) -> untyped
  private def uniqed_body_string: () -> String
  private def uniqed_body_decl: () -> RBS::AST::Declarations::t
  private def temporary_type_params: (untyped name) -> untyped
  private def type_params: (untyped name) -> untyped
  attr_reader name: String
  attr_reader body: Array[String]
  attr_accessor header: String?
  attr_accessor comment: String?
end
