# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::CreateFileByName
  @loader: Orthoses::_Call
  @to: untyped
  @header: untyped
  @depth: untyped
  @rmtree: untyped
  @if: untyped
  def initialize: (Orthoses::_Call loader, to: String, ?header: String?, ?depth: Integer?, ?rmtree: boolish) -> void
  def call: () -> Orthoses::store
end
