# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::CreateFileByName
  def initialize: (Orthoses::_Call loader, to: String, ?header: String?, ?depth: Integer?, ?rmtree: boolish) -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
end
