# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::DelegateClass
  def initialize: (Orthoses::_Call loader) -> void
  def call: () -> Orthoses::store
  def temporary_type_params: (untyped name) -> untyped
  @loader: Orthoses::_Call
end
