# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::DelegateClass
  @loader: Orthoses::_Call
  def initialize: (Orthoses::_Call loader) -> void
  def call: () -> Orthoses::store
  def temporary_type_params: (untyped name) -> untyped
end
