# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Filter
  def initialize: (Orthoses::_Call loader) { (String, Orthoses::Content) -> boolish } -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
  @block: ^(String, Orthoses::Content) -> boolish
end
