# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Filter
  @loader: Orthoses::_Call
  include Orthoses::_MiddleWare
  def initialize: (Orthoses::_Call loader, if: ^(String, Orthoses::RBSStore::Content) -> boolish) -> void
end
