# THIS IS GENERATED CODE from `$ rake sig`

# Filter current store.
# filter stored key and value if proc return true
#   use Orthoses::Filter do |name, content|
#     Orthoses.rbs_defined_class?(name)
#   end
class Orthoses::Filter
  @loader: Orthoses::_Call
  @if: untyped
  @block: ^(String, Orthoses::Content) -> boolish
  def initialize: (Orthoses::_Call loader) { (String, Orthoses::Content) -> boolish } -> void
  def call: () -> Orthoses::store
end
