# THIS IS GENERATED CODE from `$ rake sig`

# TracePoint wrapper that allows setting hooks
# even if the target is undefined
#   LazyTracePoint.new(:call) do |tp|
#     ...
#   end.enable(target: 'Class#class_attribute') do
#     require 'active_support/core_ext/class/attribute'
#     ...
#   end
class Orthoses::LazyTracePoint < ::TracePoint
  @mod_name: untyped
  @instance_method_id: untyped
  @singleton_method_id: untyped
  def enable: (?target: untyped?) ?{ () -> untyped } -> untyped
  private def trace_instance_method: () ?{ () -> untyped } -> untyped
  private def trace_singleton_method: () ?{ () -> untyped } -> untyped
  INSTANCE_METHOD_METHOD: UnboundMethod
  METHOD_ADDED_HOOKS: Hash[untyped, untyped]
  METHOD_METHOD: UnboundMethod
  SINGLETON_METHOD_ADDED_HOOKS: Hash[untyped, untyped]
  UNBOUND_NAME_METHOD: UnboundMethod
end
