# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::LazyTracePoint
  def method_added: (untyped id) -> untyped
  def singleton_method_added: (untyped id) -> untyped
  def initialize: (*untyped events) ?{ () -> untyped } -> void
  def enable: (target: untyped) ?{ () -> untyped } -> untyped
  private def trace_instance_method: () ?{ () -> untyped } -> untyped
  private def trace_singleton_method: () ?{ () -> untyped } -> untyped
end
