# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::LoadRBS
  def initialize: (Orthoses::_Call loader, paths: paths) -> void
  def call: () -> Orthoses::store
  type paths = Array[String] | ^() -> Array[String]
  @loader: Orthoses::_Call
  @paths: paths
end
