# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::LoadRBS
  def initialize: (Orthoses::_Call loader, paths: Array[_ToS]) -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
  @paths: Array[_ToS]
end
