# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::ObjectSpaceAll
  def initialize: (Orthoses::_Call loader, ?if: ^(Module) -> boolish) -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
end
