# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::ObjectSpaceAll
  @loader: Orthoses::_Call
  def initialize: (Orthoses::_Call loader, ?if: ^(Module) -> boolish) -> void
  def call: () -> Orthoses::store
end
