# THIS IS GENERATED CODE from `$ rake sig`

# Call `rbs prototype runtime` and add to store
#     use Orthoses::RBSPrototypeRuntime,
#       patterns: ['Foo::*']
class Orthoses::RBSPrototypeRuntime
  def initialize: (untyped loader, patterns: untyped) -> void
  def call: () -> untyped
end
