# THIS IS GENERATED CODE from `$ rake sig`

# Call `rbs prototype runtime` and add to store
#     use Orthoses::RBSPrototypeRuntime,
#       patterns: ['Foo::*']
class Orthoses::RBSPrototypeRuntime
  def initialize: (Orthoses::_Call loader, patterns: Array[_ToS], ?method_definition_filter: Orthoses::Content::Environment::method_definition_filter?, ?alias_filter: Orthoses::Content::Environment::alias_filter?, ?constant_filter: Orthoses::Content::Environment::constant_filter?, ?mixin_filter: Orthoses::Content::Environment::mixin_filter?, ?attribute_filter: Orthoses::Content::Environment::attribute_filter?) -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
  @patterns: Array[_ToS]
  @method_definition_filter: Orthoses::Content::Environment::method_definition_filter?
  @alias_filter: Orthoses::Content::Environment::alias_filter?
  @constant_filter: Orthoses::Content::Environment::constant_filter?
  @mixin_filter: Orthoses::Content::Environment::mixin_filter?
  @attribute_filter: Orthoses::Content::Environment::attribute_filter?
end
