# THIS IS GENERATED CODE from `$ rake sig`

# Internal middleware for return store object
# Builder set this middleware on last stack by default
class Orthoses::Store
  def initialize: (untyped loader) -> void
  def call: () -> untyped
end
