# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Trace
  @loader: untyped
  @patterns: untyped
  @sort_union_types: untyped
  def initialize: (Orthoses::_Call loader, patterns: Array[String | _CallablePatterns], ?sort_union_types: bool?) -> void
  def call: () -> Orthoses::store
end

class Orthoses::Trace::Attribute
  @loader: untyped
  @patterns: untyped
  @sort_union_types: untyped
  @captured_dict: untyped
  def initialize: (Orthoses::_Call loader, patterns: Array[String | Orthoses::Trace::_CallablePatterns], ?sort_union_types: bool?) -> void
  def call: () -> Orthoses::store
  private def build_trace_hook: () -> untyped
  include Orthoses::Trace::Targetable
end

module Orthoses::Trace::Attribute::Hook
  def attr: (*untyped names) -> untyped

  def attr_accessor: (*untyped names) -> untyped

  def attr_reader: (*untyped names) -> untyped

  def attr_writer: (*untyped names) -> untyped
end

class Orthoses::Trace::Method
  @loader: untyped
  @patterns: untyped
  @sort_union_types: untyped
  @stack: untyped
  @args_return_map: untyped
  @alias_map: untyped
  def initialize: (Orthoses::_Call loader, patterns: Array[String | Orthoses::Trace::_CallablePatterns], ?sort_union_types: bool?) -> void
  def call: () -> Orthoses::store
  private def build_trace_point: () -> untyped
  private def build_members: () -> untyped
  private def build_method_definitions: () -> untyped
  private def build_aliases: () -> untyped
  include Orthoses::Trace::Targetable
end

class Orthoses::Trace::Method::Info < ::Struct[untyped]
end

module Orthoses::Trace::Targetable
  def target?: (untyped name, untyped tp) -> untyped
end

interface Orthoses::Trace::_CallablePatterns
  def call: (String, TracePoint) -> bool
end
