# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Walk
  @loader: Orthoses::_Call
  @root: Module | String
  def initialize: (Orthoses::_Call loader, root: Module | String) -> void
  def call: () -> Orthoses::store
end
