# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Writer
  def initialize: (Orthoses::_Call loader, io: _Writer) -> void
  def call: () -> Orthoses::store
  @loader: Orthoses::_Call
end
