module Orthoses
  class RBSStore
    class Buffer
      type decl = (RBS::AST::Declarations::Class | RBS::AST::Declarations::Module | RBS::AST::Declarations::Interface)?
      attr_reader env: RBS::Environment
      attr_reader type_name: RBS::TypeName
      attr_reader lines: Array[String]
      attr_accessor decl: decl

      def initialize: (env: RBS::Environment, type_name: RBS::TypeName , ?lines: Array[String], ?decl: decl) -> void
      def <<: (String) -> void
      def resolve!: () -> void

      private

      def auto_set_decl: () -> void
      def key_name: () -> String
      def name_and_params: (RBS::TypeName, Array[RBS::AST::TypeParam]) -> String
      def name_and_args: (RBS::TypeName, Array[RBS::AST::TypeParam]) -> String
    end
  end
end
