module Orthoses
  class RBSStore
    class Content
      attr_reader name: String
      attr_reader body: Array[String]
      attr_accessor header: String?

      def initialize: (name: String) -> void
      def <<: (String) -> void
      def concat: (Array[String]) -> void
      def to_rbs: () -> String
    end
  end
end
