# THIS IS GENERATED CODE from `$ rake sig`

class Orthoses::Trace::Attribute
  def initialize: (untyped loader, patterns: untyped) -> void
  def call: () -> untyped
  private def build_trace_hook: () -> untyped
  include Orthoses::Trace::Targetable
end
