# THIS IS GENERATED CODE from `$ rake generate_self_sig`

class Orthoses::Trace::Method
  def initialize: (untyped loader, patterns: untyped) -> void
  def call: () -> untyped
  private def build_trace_point: () -> untyped
  private def build_members: () -> untyped
  private def build_method_definitions: () -> untyped
  private def build_aliases: () -> untyped
  include Orthoses::Trace::Targetable
end
