module Orthoses
  class Builder
    def initialize: () ?{ () [self: Orthoses::Builder] -> untyped } -> void
    def use: (untyped middleware, *untyped args, **untyped key) ?{ () -> untyped } -> untyped
    def call: () -> Orthoses::store
  end
end
