module Orthoses
  class CallTracer
    class Result < ::Struct[untyped]
      def method: () -> Method
      def argument: () -> Hash[Symbol, untyped]
    end

    attr_accessor results: Array[Result]
    def trace: [T] (Method | UnboundMethod) ?{ () -> T } -> T
  end
end
