module Orthoses
  class CallTracer
    class Capture < ::Struct[untyped]
      def method: () -> Method
      def argument: () -> Hash[Symbol, untyped]
    end

    attr_accessor captures: Array[Capture]
    def trace: [T] (Method | UnboundMethod) ?{ () -> T } -> T
  end
end
