module Orthoses
  class CallTracer
    module Capturable
      module ExtractRestParameters
        def __extract_rest_parameters__: (*untyped rest, **untyped kw_rest) { (*untyped, **untyped) -> untyped } -> untyped
      end
    end
    class Capture < ::Struct[untyped]
      def method: () -> Method
      def argument: () -> Hash[Symbol, untyped]
    end

    attr_accessor captures: Array[Capture]
    def trace: (Method | UnboundMethod) ?{ () -> untyped } -> untyped

    class Lazy
      attr_reader captures: Array[untyped]
      def initialize: () -> void
      def trace: (String name) ?{ () -> untyped } -> untyped
      attr_reader captures: Array[Orthoses::CallTracer::Capture]
    end
  end
end
