module Orthoses
  class Content
    attr_reader name: String
    attr_reader body: Array[String]
    attr_accessor header: String?

    def initialize: (name: String) -> void
    def <<: (String) -> void
    def concat: (Array[String]) -> void
    def to_rbs: () -> String

    private

    def uniqed_body_string: () -> String
    def uniqed_body_decl: () -> RBS::AST::Declarations::t
  end
end
