module Orthoses
  class CreateFileByName
    @loader: Orthoses::_Call
    def initialize: (Orthoses::_Call loader, base_dir: String, ?header: String?, ?depth: Integer?) -> void
    def call: () -> Orthoses::store
  end
end
