module Orthoses
  class CreateFileByName
    @loader: Orthoses::_Call
    include Orthoses::_MiddleWare
    def initialize: (Orthoses::_Call loader, base_dir: String, ?header: String?) -> void
  end
end
