module Orthoses
  class CreateFileByName
    @loader: Orthoses::_Call
    def initialize: (Orthoses::_Call loader, to: String, ?header: String?, ?depth: Integer | Hash[String, Integer] | nil, ?rmtree: boolish) -> void
    def call: () -> Orthoses::store
  end
end
