module Orthoses
  class Filter
    @loader: Orthoses::_Call
    @block: ^(String, Orthoses::Content) -> boolish
    def initialize: (Orthoses::_Call loader) { (String, Orthoses::Content) -> boolish } -> void
    def call: () -> Orthoses::store
  end
end
