module Orthoses
  class LazyTracePoint < ::TracePoint
    def enable: (?target: untyped?) ?{ () -> untyped } -> untyped
    private def trace_instance_method: () ?{ () -> untyped } -> untyped
    private def trace_singleton_method: () ?{ () -> untyped } -> untyped
  end
end
