module Orthoses
  class LoadRBS
    @loader: Orthoses::_Call
    @paths: Array[_ToS]
    def initialize: (Orthoses::_Call loader, paths: Array[_ToS]) -> void
    def call: () -> Orthoses::store
  end
end
