module Orthoses
  class LoadRBS
    type paths = Array[String] | ^() -> Array[String]

    @loader: Orthoses::_Call
    @paths: paths
    def initialize: (Orthoses::_Call loader, paths: paths) -> void
    def call: () -> Orthoses::store
  end
end
