module Orthoses
  class Mixin
    @loader: Orthoses::_Call
    def initialize: (Orthoses::_Call loader) -> void
    def call: () -> Orthoses::store

    private

    def collect_definitions: (Orthoses::store store, Orthoses::CallTracer call_tracer, (:include | :extend | :prepend) how) -> void
  end
end
