module Orthoses
  class Mixin
    CALL_GRAPH: Hash[untyped, [:include | :extend | :prepend, untyped]]

    module Hook : Module
    end

    @loader: Orthoses::_Call
    def initialize: (Orthoses::_Call loader, ?if: nil | ^(Module base_mod, (:include | :extend | :prepend) how, Module mod) -> boolish) -> void
    def call: () -> Orthoses::store

    private def type_params_sig: (untyped mod) -> String
  end
end
