module Orthoses
  class Walk
    @loader: Orthoses::_Call
    @root: Module | String
    include Orthoses::_MiddleWare
    def initialize: (Orthoses::_Call loader, root: Module | String) -> void
  end
end
