# THIS IS GENERATED CODE from `$ rake sig`

module Orthoses::Mixin::Hook
  def include: (*untyped modules) -> untyped

  def extend: (*untyped modules) -> untyped

  def prepend: (*untyped modules) -> untyped
end
